const RAW="https://raw.githubusercontent.com/AlbaGG95/casas-catalunya/main/data/listings.json";
const $=s=>document.querySelector(s),els={grid:$("#listingGrid"),empty:$("#emptyState"),search:$("#searchInput"),province:$("#provinceFilter"),budget:$("#budgetFilter"),status:$("#statusFilter"),sort:$("#sortFilter"),visible:$("#visibleCount"),newCount:$("#newCount"),under180:$("#under180Count"),savedCount:$("#savedCount"),updatedAt:$("#updatedAt"),lastScan:$("#lastScan"),sourceHealth:$("#sourceHealth"),toast:$("#toast")};
let payload={listings:[],sourceStatus:{}},known=new Set(),saved=new Set(JSON.parse(localStorage.getItem("savedHomes")||"[]"));
const euro=n=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n),fmt=v=>v?new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—",hours=v=>v?(Date.now()-new Date(v))/36e5:1e9,esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])),safe=u=>{try{let x=new URL(u);return /^https?:$/.test(x.protocol)?x:""}catch{return""}};
const date=h=>h.publishedAt||((h.freshnessEvidence==="recent_source")?h.firstSeen:null),recent=h=>h.freshnessStatus==="recent"||hours(date(h))<=336,new48=h=>recent(h)&&hours(date(h))<=48,stretch=h=>h.price>180000&&h.price<=185000,candidate=h=>h.active!==false&&h.freshnessStatus!=="old"&&h.occupancyStatus!=="blocked"&&h.financingStatus!=="blocked";
function tag(t,c=""){return '<span class="tag '+c+'">'+esc(t)+'</span>'}function check(t,s){return '<span class="check '+s+'">'+(s==="ok"?"✓ ":s==="pending"?"⚠ ":"• ")+esc(t)+'</span>'}
function toast(t){els.toast.textContent=t;els.toast.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.hidden=true,4500)}
function card(h){let ts=[];if(new48(h))ts.push(tag("Nueva ≤48h","new"));else if(recent(h))ts.push(tag("Reciente","new"));if((h.score||0)>=84)ts.push(tag("Buen encaje","fit"));if(h.occupancyStatus==="confirmed_free")ts.push(tag("Libre indicada","free"));if(stretch(h))ts.push(tag("180–185k","stretch"));if(h.registryStatus!=="verified")ts.push(tag("Nota simple pendiente","pending"));
let img=safe(h.imageUrl),media=img?'<div class="card-media"><img loading="lazy" referrerpolicy="no-referrer" src="'+esc(img)+'"><span class="media-badge">'+(new48(h)?"Nueva":"Candidata")+'</span></div>':'<div class="card-media"><div class="photo-fallback">Foto en anuncio original</div><span class="media-badge">'+(new48(h)?"Nueva":"Candidata")+'</span></div>';
let travel=h.driveMinutes!=null?Math.round(h.driveMinutes)+" min aprox.":"Distancia pendiente",link=safe(h.url),sv=saved.has(h.id);
return '<article class="card">'+media+'<div class="card-body"><div class="card-top"><div class="tags">'+ts.join("")+'</div><span class="score">'+esc(h.score||0)+'/100</span></div><div><div class="price">'+euro(h.price)+(stretch(h)?'<small>margen</small>':"")+'</div><h2>'+esc(h.title)+'</h2><div class="place">'+esc(h.place||"Localidad por identificar")+' · '+esc(h.province||"Cataluña")+'</div></div><div class="features"><span>'+esc(h.bedrooms||"3+")+' hab.</span>'+(h.houseM2?'<span>'+esc(h.houseM2)+' m² casa</span>':"")+(h.plotM2?'<span>'+esc(h.plotM2)+' m² parcela</span>':"")+'<span>'+esc(travel)+'</span></div><p>'+esc(h.summary||"Candidata detectada automáticamente.")+'</p><div class="checks">'+check("Jardín/parcela","ok")+check(h.independentStatus==="confirmed"?"Independiente":"Tipología por confirmar",h.independentStatus==="confirmed"?"ok":"pending")+check(h.conditionStatus==="confirmed"?"Estado para entrar":"Estado por confirmar",h.conditionStatus==="confirmed"?"ok":"pending")+check(h.occupancyStatus==="confirmed_free"?"Libre indicada":"Sin señales de ocupación",h.occupancyStatus==="confirmed_free"?"ok":"pending")+check("Sin restricción bancaria detectada","ok")+check(h.registryStatus==="claimed_clear"?"Libre de cargas según anuncio":"Nota simple pendiente",h.registryStatus==="claimed_clear"?"ok":"pending")+'</div><div class="meta"><span>'+esc(h.provider)+'</span><span>Detectada '+fmt(h.firstSeen)+'</span><span>Revisada '+fmt(h.lastSeen||h.lastChecked)+'</span></div><div class="actions"><button class="'+(sv?"saved":"")+'" data-save="'+esc(h.id)+'">'+(sv?"Quitar":"Guardar")+'</button>'+(link?'<a href="'+esc(link)+'" target="_blank" rel="noopener">Ver anuncio</a>':"")+'</div></div></article>'}
function render(){let a=(payload.listings||[]).filter(candidate),q=els.search.value.toLowerCase().trim(),p=els.province.value,b=els.budget.value,s=els.status.value;if(q)a=a.filter(h=>(h.title+" "+(h.place||"")).toLowerCase().includes(q));if(p)a=a.filter(h=>h.province===p);if(b==="180")a=a.filter(h=>h.price<=180000);else if(b==="smart185")a=a.filter(h=>h.price<=180000||(h.price<=185000&&(h.score||0)>=78));if(s==="new")a=a.filter(recent);if(s==="best")a=a.filter(h=>(h.score||0)>=84);if(s==="independent")a=a.filter(h=>h.independentStatus==="confirmed");if(s==="free")a=a.filter(h=>h.occupancyStatus==="confirmed_free");if(s==="pending")a=a.filter(h=>h.conditionStatus!=="confirmed"||h.independentStatus!=="confirmed"||h.registryStatus!=="verified");if(s==="saved")a=a.filter(h=>saved.has(h.id));let so=els.sort.value,d=h=>new Date(date(h)||h.firstSeen||0);if(so==="recent")a.sort((x,y)=>d(y)-d(x)||(y.score||0)-(x.score||0));else if(so==="score")a.sort((x,y)=>(y.score||0)-(x.score||0));else if(so==="price-asc")a.sort((x,y)=>x.price-y.price);else a.sort((x,y)=>y.price-x.price);els.grid.innerHTML=a.map(card).join("");els.empty.hidden=!!a.length;let all=(payload.listings||[]).filter(candidate);els.visible.textContent=a.length;els.newCount.textContent=all.filter(recent).length;els.under180.textContent=all.filter(h=>h.price<=180000).length;els.savedCount.textContent=saved.size;els.updatedAt.textContent="Datos "+fmt(payload.generatedAt);els.lastScan.textContent=fmt(payload.generatedAt);let st=Object.values(payload.sourceStatus||{});els.sourceHealth.textContent=st.length?st.filter(x=>x?.ok).length+"/"+st.length+" OK":"—";document.querySelectorAll("[data-save]").forEach(x=>x.onclick=()=>{let id=x.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem("savedHomes",JSON.stringify([...saved]));render()})}
async function load(silent=false){try{let r=await fetch(RAW+"?t="+Date.now(),{cache:"no-store"}),n=await r.json(),ids=new Set((n.listings||[]).filter(candidate).map(x=>x.id));if(silent&&known.size){let added=[...ids].filter(x=>!known.has(x));if(added.length)toast("🏠 "+added.length+" nueva"+(added.length>1?"s":"")+" candidata"+(added.length>1?"s":""));}payload=n;known=ids;render()}catch(e){console.error(e)}}
[els.search,els.province,els.budget,els.status,els.sort].forEach(x=>x.addEventListener(x===els.search?"input":"change",render));load();setInterval(()=>load(true),30000);